AVR-DRV: /home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/spi.c File Reference
/home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/spi.c File Reference
Code for SPI module.
#include <stdbool.h>
#include <stdint.h>
#include <avr/io.h>
#include "avr-drv-errno.h"
#include "spi.h"
#include "io_pin/io_pin.h"
Functions
void spi_enable (void)
Enable SPI block.
void spi_disable (void)
Disable SPI block.
void spi_int_enable (void)
Enable interrupt for SPI block.
void spi_int_disable (void)
Disable interrupt for SPI block.
void spi_init (_Bool isMsb, spi_op_mode_t opMode, spi_mode_t mode, spi_prescaler_t scaler)
Configure the SPI port.
void spi_set_operation_mode (spi_op_mode_t mode)
Configure SPI in Slave or Master operation mode.
void spi_set_mode (spi_mode_t mode)
Configure SPI operation mode.
void spi_set_msb_lsb (_Bool isMsb)
void spi_set_prescaler (spi_prescaler_t scaler)
Configure SPI clock to be use in Master mode.
void spi_transfer (uint8_t ubDataOut, uint8_t *pubDataIn)
Send byte over SPI bus.
void spi_transferISR (uint8_t ubDataOut, uint8_t *pubDataIn)
Start a new byte transfer and get last byte in, use only in ISR function.
Detailed Description
Code for SPI module.
Author:
Frédéric Nadeau
Definition in file spi.c.
Function Documentation
void spi_disable (void)
Disable SPI block.
Definition at line 83 of file spi.c.
void spi_enable (void)
Enable SPI block.
Definition at line 78 of file spi.c.
Referenced by spi_init().
void spi_init (_Bool isMsb, spi_op_mode_t masterSlaveMode, spi_mode_t mode, spi_prescaler_t scaler)
Configure the SPI port.
Parameters:
isMsb true if MSB fist, false for LSB first.
masterSlaveMode use spi_op_mode_t to select operation mode.
mode Use spi_mode_t to select
scaler Use spi_prescaler_t to select clock prescaler.
Definition at line 98 of file spi.c.
References spi_enable(), spi_set_mode(), spi_set_msb_lsb(), spi_set_operation_mode(), and spi_set_prescaler().
void spi_int_disable (void)
Disable interrupt for SPI block.
Definition at line 93 of file spi.c.
void spi_int_enable (void)
Enable interrupt for SPI block.
Definition at line 88 of file spi.c.
void spi_set_mode (spi_mode_t mode)
Configure SPI operation mode.
Parameters:
mode use spi_mode_t, see Atmel documentation.
Definition at line 140 of file spi.c.
References spi_mode_0, spi_mode_1, spi_mode_2, and spi_mode_3.
Referenced by spi_init().
void spi_set_msb_lsb (_Bool isMsb)
Definition at line 163 of file spi.c.
Referenced by spi_init().
void spi_set_operation_mode (spi_op_mode_t mode)
Configure SPI in Slave or Master operation mode.
Parameters:
mode use spi_op_mode_t to select master or slave mode.
Definition at line 108 of file spi.c.
References spi_op_mode_multi_mMaster, spi_op_mode_single_master, and spi_op_mode_slave.
Referenced by spi_init().
void spi_set_prescaler (spi_prescaler_t scaler)
Configure SPI clock to be use in Master mode.
Parameters:
scaler Division factor, use spi_prescaler_t to select clock source.
Definition at line 175 of file spi.c.
References spi_prescaler_128, spi_prescaler_16, spi_prescaler_2, spi_prescaler_32, spi_prescaler_4, spi_prescaler_64, and spi_prescaler_8.
Referenced by spi_init().
void spi_transfer (uint8_t ubDataOut, uint8_t * pubDataIn)
Send byte over SPI bus.
Parameters:
ubDataOut Data to be send.
pubDataIn Pointer to 8 bit data space. Red value will be saved at specified address.
Definition at line 221 of file spi.c.
void spi_transferISR (uint8_t ubDataOut, uint8_t * pubDataIn)
Start a new byte transfer and get last byte in, use only in ISR function.
Parameters:
ubDataOut Data to be send.
pubDataIn Pointer to 8 bit data space. Read value will be saved at specified address. If address is (void*) 0, received data will be discarded.
Definition at line 238 of file spi.c.