AVR-DRV: /home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/spi.h File Reference
/home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/spi.h File Reference
API for Atmel SPI module.
#include <stdint.h>
Typedefs
typedef enum spi_op_mode_e spi_op_mode_t
typedef enum spi_mode_e spi_mode_t
typedef enum spi_prescaler_e spi_prescaler_t
Enumerations
enum spi_op_mode_e { spi_op_mode_single_master = 0, spi_op_mode_multi_mMaster, spi_op_mode_slave }
enum spi_mode_e { spi_mode_0 = 0, spi_mode_1, spi_mode_2, spi_mode_3 }
enum spi_prescaler_e {
spi_prescaler_2 = 0, spi_prescaler_4, spi_prescaler_8, spi_prescaler_16,
spi_prescaler_32, spi_prescaler_64, spi_prescaler_128
}
Functions
void spi_enable (void)
Enable SPI block.
void spi_disable (void)
Disable SPI block.
void spi_int_enable (void)
Enable interrupt for SPI block.
void spi_int_disable (void)
Disable interrupt for SPI block.
void spi_init (_Bool isMsb, spi_op_mode_t masterSlaveMode, spi_mode_t mode, spi_prescaler_t scaler)
Configure the SPI port.
void spi_set_operation_mode (spi_op_mode_t mode)
Configure SPI in Slave or Master operation mode.
void spi_set_mode (spi_mode_t mode)
Configure SPI operation mode.
void spi_set_msb_lsb (_Bool isMsb)
void spi_set_prescaler (spi_prescaler_t scaler)
Configure SPI clock to be use in Master mode.
void spi_transfer (uint8_t ubDataOut, uint8_t *pubDataIn)
Send byte over SPI bus.
void spi_transferISR (uint8_t ubDataOut, uint8_t *pubDataIn)
Start a new byte transfer and get last byte in, use only in ISR function.
Detailed Description
API for Atmel SPI module.
Author:
Frédéric Nadeau
Definition in file spi.h.
Typedef Documentation
typedef enum spi_mode_e spi_mode_t
typedef enum spi_op_mode_e spi_op_mode_t
typedef enum spi_prescaler_e spi_prescaler_t
Enumeration Type Documentation
enum spi_mode_e
Enumerator:
spi_mode_0
CPOL = 0, CPHA = 0
spi_mode_1
CPOL = 0, CPHA = 1
spi_mode_2
CPOL = 1, CPHA = 0
spi_mode_3
CPOL = 1, CPHA = 1
Definition at line 54 of file spi.h.
enum spi_op_mode_e
Enumerator:
spi_op_mode_single_master
SPI act as a single master on bus. Chip Select pin will be configured as output to prevent fallback to slave mode.
spi_op_mode_multi_mMaster
SPI is configured as master but can fall back as slave if Chip Select pin is driven low.
spi_op_mode_slave
Definition at line 43 of file spi.h.
enum spi_prescaler_e
Enumerator:
spi_prescaler_2
OSCCLK/2
spi_prescaler_4
OSCCLK/4
spi_prescaler_8
OSCCLK/8
spi_prescaler_16
OSCCLK/16
spi_prescaler_32
OSCCLK/32
spi_prescaler_64
OSCCLK/64
spi_prescaler_128
OSCCLK/128
Definition at line 62 of file spi.h.
Function Documentation
void spi_disable (void)
Disable SPI block.
Definition at line 83 of file spi.c.
void spi_enable (void)
Enable SPI block.
Definition at line 78 of file spi.c.
Referenced by spi_init().
void spi_init (_Bool isMsb, spi_op_mode_t opMode, spi_mode_t mode, spi_prescaler_t scaler)
Configure the SPI port.
Parameters:
isMsb true if MSB fist, false for LSB first.
masterSlaveMode use spi_op_mode_t to select operation mode.
mode Use spi_mode_t to select
scaler Use spi_prescaler_t to select clock prescaler.
Definition at line 98 of file spi.c.
References spi_enable(), spi_set_mode(), spi_set_msb_lsb(), spi_set_operation_mode(), and spi_set_prescaler().
void spi_int_disable (void)
Disable interrupt for SPI block.
Definition at line 93 of file spi.c.
void spi_int_enable (void)
Enable interrupt for SPI block.
Definition at line 88 of file spi.c.
void spi_set_mode (spi_mode_t mode)
Configure SPI operation mode.
Parameters:
mode use spi_mode_t, see Atmel documentation.
Definition at line 140 of file spi.c.
References spi_mode_0, spi_mode_1, spi_mode_2, and spi_mode_3.
Referenced by spi_init().
void spi_set_msb_lsb (_Bool isMsb)
Definition at line 163 of file spi.c.
Referenced by spi_init().
void spi_set_operation_mode (spi_op_mode_t mode)
Configure SPI in Slave or Master operation mode.
Parameters:
mode use spi_op_mode_t to select master or slave mode.
Definition at line 108 of file spi.c.
References spi_op_mode_multi_mMaster, spi_op_mode_single_master, and spi_op_mode_slave.
Referenced by spi_init().
void spi_set_prescaler (spi_prescaler_t scaler)
Configure SPI clock to be use in Master mode.
Parameters:
scaler Division factor, use spi_prescaler_t to select clock source.
Definition at line 175 of file spi.c.
References spi_prescaler_128, spi_prescaler_16, spi_prescaler_2, spi_prescaler_32, spi_prescaler_4, spi_prescaler_64, and spi_prescaler_8.
Referenced by spi_init().
void spi_transfer (uint8_t ubDataOut, uint8_t * pubDataIn)
Send byte over SPI bus.
Parameters:
ubDataOut Data to be send.
pubDataIn Pointer to 8 bit data space. Red value will be saved at specified address.
Definition at line 221 of file spi.c.
void spi_transferISR (uint8_t ubDataOut, uint8_t * pubDataIn)
Start a new byte transfer and get last byte in, use only in ISR function.
Parameters:
ubDataOut Data to be send.
pubDataIn Pointer to 8 bit data space. Read value will be saved at specified address. If address is (void*) 0, received data will be discarded.
Definition at line 238 of file spi.c.