AVR-DRV: /home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/usartBaudRate.h File Reference
/home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/usartBaudRate.h File Reference
Function definition for USART baud rate calculation.
Functions
int usart_baud_rate_get_ubrb (uint32_t uiBaudRate, uint32_t uiClk, uint8_t ubTol, usart_mode_t mode, uint16_t *puwUbrr)
Compute value for UBRR.
Detailed Description
Function definition for USART baud rate calculation.
Definition in file usartBaudRate.h.
Function Documentation
int usart_baud_rate_get_ubrb (uint32_t uiBaudRate, uint32_t uiClk, uint8_t ubTol, usart_mode_t mode, uint16_t * puwUbrr)
Compute value for UBRR.
Parameters:
uiBaudRate Desired baud rate.
uiClk Clock frequency in Hz.
ubTol Mismatch tolerance. 2 should be use, witch mean 2%.
mode Whether it is Asyn or Sync USART mode.
puwUbrr Pointer to where UBRR value will be saved.
Returns:
On success, value can be 0 or 1. If value is 0, X2 mode shall be desactivated and if it is 1, it shall be activated. Value -1 indicate that an error occurred. See errno for detail on error.
EINVAL Invalid argument was provided.
EBAUDRATE Desired baud rate can not be achieved.
Definition at line 74 of file usartBaudRate.c.
References avr_drv_errno, check_Tol(), EBAUDRATE, EINVAL, get_ubrb(), usart_mode_async, usart_mode_sync_master, and usart_mode_sync_slave.
Referenced by usart_set_baud_rate().