AVR-DRV: /home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/usart.h File Reference
/home/fnadeau/EclipseWorkspaces/avrdrv/avr-drv/trunk/src/usart.h File Reference
Function and type definitions for USART module.
Data Structures
struct usart_port_s
Typedefs
typedef struct usart_port_s usart_port_t
typedef enum usart_bit_e usart_bit_t
typedef enum usart_parity_e usart_parity_t
typedef enum usart_stop_bit_e usart_stop_bit_t
typedef enum usart_mode_e usart_mode_t
Enumerations
enum usart_bit_e {
usart_bit_5 = 0, usart_bit_6, usart_bit_7, usart_bit_8,
usart_bit_9 = 7
}
enum usart_parity_e { usart_parity_None = 0, usart_parity_Even = 2, usart_parity_Odd = 3 }
enum usart_stop_bit_e { usart_stop_bit_1 = 0, usart_stop_bit_2 }
enum usart_mode_e { usart_mode_async, usart_mode_sync_master, usart_mode_sync_slave }
Functions
int usart_init (usart_port_t *port, uint32_t ulBaudRate, uint32_t uiClk, usart_bit_t bit, usart_parity_t parity, usart_stop_bit_t stopBit, usart_mode_t mode)
int usart_set_baud_rate (usart_port_t *port, uint32_t ulBaudrate, uint32_t uiClk, usart_mode_t mode)
void usart_set_num_bit (usart_port_t *port, usart_bit_t numbit)
void usart_set_parity (usart_port_t *port, usart_parity_t partity)
void usart_set_stop_bit (usart_port_t *port, usart_stop_bit_t stopbit)
void usart_set_mode (usart_port_t *port, usart_mode_t mode)
void usart_enable_rx (usart_port_t *port, _Bool enable)
void usart_enable_tx (usart_port_t *port, _Bool enable)
int usart_putc (usart_port_t *port, char data)
int usart_getc (usart_port_t *port, char *data)
void usart_enable_rx_int (usart_port_t *port, _Bool enable)
void usart_enable_tx_buf_int (usart_port_t *port, _Bool enable)
void usart_enable_tx_cmp_int (usart_port_t *port, _Bool enable)
void usart_putc_isr (usart_port_t *port, char data)
int usart_getc_isr (usart_port_t *port, char *data)
Detailed Description
Function and type definitions for USART module.
Author:
Frédéric Nadeau
Definition in file usart.h.
Typedef Documentation
typedef enum usart_bit_e usart_bit_t
< Number of bits used by the USART module. Typedef of usart_bit_e.
typedef enum usart_mode_e usart_mode_t
< Mode into witch USART will be configured. Typedef for usart_mode_e.
typedef enum usart_parity_e usart_parity_t
< Parity bit that will be added to frame. Typedef for usart_parity_e.
typedef struct usart_port_s usart_port_t
typedef enum usart_stop_bit_e usart_stop_bit_t
< How many stop bit will be added to frame. Typedef for usart_stop_bit_e.
Enumeration Type Documentation
enum usart_bit_e
< Number of bits used by the USART module.
Enumerator:
usart_bit_5
USART use 5 bits.
usart_bit_6
USART use 6 bits.
usart_bit_7
USART use 7 bits.
usart_bit_8
USART use 8 bits.
usart_bit_9
USART use 9 bits.
Definition at line 101 of file usart.h.
enum usart_mode_e
< Mode into witch USART will be configured.
Enumerator:
usart_mode_async
Asynchronous, Most likely what you need.
usart_mode_sync_master
Synchronous mode. We are the clock source.
usart_mode_sync_slave
Synchronous mode. Clock source must be provided.
Definition at line 123 of file usart.h.
enum usart_parity_e
< Parity bit that will be added to frame.
Enumerator:
usart_parity_None
No parity bit.
usart_parity_Even
Use even parity bit.
usart_parity_Odd
Use odd parity bit.
Definition at line 110 of file usart.h.
enum usart_stop_bit_e
< How many stop bit will be added to frame.
Enumerator:
usart_stop_bit_1
Add one stop bit.
usart_stop_bit_2
Add two stop bit.
Definition at line 117 of file usart.h.
Function Documentation
void usart_enable_rx (usart_port_t * port, _Bool enable)
Definition at line 377 of file usart.c.
References RXEN, and usart_port_s::ucsrb.
void usart_enable_rx_int (usart_port_t * port, _Bool enable)
Definition at line 469 of file usart.c.
References RXCIE, and usart_port_s::ucsrb.
void usart_enable_tx (usart_port_t * port, _Bool enable)
Definition at line 389 of file usart.c.
References TXEN, and usart_port_s::ucsrb.
void usart_enable_tx_buf_int (usart_port_t * port, _Bool enable)
Definition at line 481 of file usart.c.
References usart_port_s::ucsrb, and UDRE.
void usart_enable_tx_cmp_int (usart_port_t * port, _Bool enable)
Definition at line 493 of file usart.c.
References TXCIE, and usart_port_s::ucsrb.
int usart_getc (usart_port_t * port, char * data)
Definition at line 417 of file usart.c.
References avr_drv_errno, DOR, ERXDISABLED, ERXFRAM, ERXMULTI, ERXOVERRUN, ERXPARITY, FE, PE, RXC, RXEN, usart_port_s::ucsra, usart_port_s::ucsrb, usart_port_s::udr, and USART_RX_ERR_MASK.
int usart_getc_isr (usart_port_t * port, char * data)
Definition at line 510 of file usart.c.
References avr_drv_errno, DOR, ERXFRAM, ERXMULTI, ERXOVERRUN, ERXPARITY, FE, PE, usart_port_s::ucsra, usart_port_s::udr, and USART_RX_ERR_MASK.
int usart_init (usart_port_t * port, uint32_t ulBaudRate, uint32_t uiClk, usart_bit_t bit, usart_parity_t parity, usart_stop_bit_t stopBit, usart_mode_t mode)
Definition at line 253 of file usart.c.
References usart_set_baud_rate(), usart_set_mode(), usart_set_num_bit(), usart_set_parity(), and usart_set_stop_bit().
int usart_putc (usart_port_t * port, char data)
Definition at line 401 of file usart.c.
References avr_drv_errno, ETXDISABLED, TXEN, usart_port_s::ucsra, usart_port_s::ucsrb, usart_port_s::udr, and UDRE.
void usart_putc_isr (usart_port_t * port, char data)
Definition at line 505 of file usart.c.
References usart_port_s::udr.
int usart_set_baud_rate (usart_port_t * port, uint32_t ulBaudrate, uint32_t uiClk, usart_mode_t mode)
Definition at line 273 of file usart.c.
References U2X, usart_port_s::ubrrh, usart_port_s::ubrrl, usart_port_s::ucsra, and usart_baud_rate_get_ubrb().
Referenced by usart_init().
void usart_set_mode (usart_port_t * port, usart_mode_t mode)
Definition at line 357 of file usart.c.
References usart_port_s::ucsrc, UMSEL, usart_mode_async, usart_mode_sync_master, usart_mode_sync_slave, write_to_ucsrc, usart_port_s::xck_bit, and usart_port_s::xck_ddr.
Referenced by usart_init().
void usart_set_num_bit (usart_port_t * port, usart_bit_t numbit)
Definition at line 317 of file usart.c.
References usart_port_s::ucsrb, usart_port_s::ucsrc, UCSZ0, UCSZ1, UCSZ2, usart_bit_5, usart_bit_6, usart_bit_7, usart_bit_8, usart_bit_9, and write_to_ucsrc.
Referenced by usart_init().
void usart_set_parity (usart_port_t * port, usart_parity_t partity)
Definition at line 338 of file usart.c.
References usart_port_s::ucsrc, UPM0, UPM1, and write_to_ucsrc.
Referenced by usart_init().
void usart_set_stop_bit (usart_port_t * port, usart_stop_bit_t stopbit)
Definition at line 344 of file usart.c.
References usart_port_s::ucsrc, usart_stop_bit_1, USBS, and write_to_ucsrc.
Referenced by usart_init().